import os
from django.core.exceptions import ValidationError


def file_size_validator(value):
    pass
